### ISSUE TITLE
The error continues to occur. Is there a way to take action?

### ISSUE THREAD

**Issue by GreenPine-CK** [ArduPilot/SITL_Models#107]
lck@aaa:~/gz_ws/src$ gz sim -v4 -r skycat_runway.sdf
**[Wrn] [gz.cc:102] Fuel world download failed because Fetch failed. Other errors**

bashrc에
export GZ_SIM_RESOURCE_PATH=$GZ_SIM_RESOURCE_PATH:\
$HOME/SITL_Models/Gazebo/models:
$HOME/SITL_Models/Gazebo/worlds

I added it and proceeded with the source ~/.bashrc,
It doesn't work.

Someone tell me how to do it

*iris_runway or zephyr runs well

thank you.

**Comment by srmainwaring** [comment]
@GreenPine-CK, this looks like an issue with your resource path. What directory did you clone SITL_Models to? Can you also provide the full console output and the value of `echo $GZ_SIM_RESOURCE_PATH`.

**Comment by GreenPine-CK** [comment]
The directory path is **/home/lck/gz_ws/src/ardupilot_gazebo/models** 
![bashrc-path-1](https://github.com/ArduPilot/SITL_Models/assets/70504100/3f736102-3ecc-4d6f-b7ad-fd253d2d0b67)
Which path should I enter in the bashrc? Thank you for your interest.

**Comment by srmainwaring** [comment]
Have you copied the skyca_tvbs model to `ardupilot_gazebo/models`? If that's the case then you won't have the world file in your path. The expectation is you clone this repo and set the path to that location. In your case:

```bash
cd  /home/lck/gz_ws/src/
git clone https://github.com/ArduPilot/SITL_Models.git
export GZ_SIM_RESOURCE_PATH=$GZ_SIM_RESOURCE_PATH:/home/lck/gz_ws/src/SITL_Models/Gazebo/models::/home/lck/gz_ws/src/SITL_Models/Gazebo/worlds
```

and you should remove the copy from `ardupilot_gazebo/models`.

**Comment by GreenPine-CK** [comment]
![advice1](https://github.com/ArduPilot/SITL_Models/assets/70504100/6d4322b7-2ff2-4e58-8d8f-89b3c734653c)

There seems to be an unexpected error..
I'm trying again, and I'll ask you a question again. 

Thanks once again.

**Comment by GreenPine-CK** [comment]
This issue has been resolved.
It was my mistake. Thank you for your reply.
