### ISSUE TITLE
Where is 'waves' world?

### ISSUE THREAD

**Issue by dlaboy** [ArduPilot/SITL_Models#123]
I can't find waves world for catamaran_waves.sdf

**Comment by srmainwaring** [comment]
The instructions for setting up the model and dependencies are here: https://github.com/ArduPilot/SITL_Models/blob/master/Gazebo/docs/Catamaran.md.

**Comment by dlaboy** [comment]
Thanks!

**Comment by dlaboy** [comment]
Apparently a have read the documentation. I want to set up BlueBoat. My question was because of this step 
<img width="1047" alt="Screenshot 2024-02-21 at 4 34 20 PM" src="https://github.com/ArduPilot/SITL_Models/assets/89310701/236b367b-b057-47dd-a82e-f5b441563e65">
Which tells me to add the line to the waves.sdf world. Could you help me figure this out?

**Comment by dlaboy** [comment]
So at the end, on my environment variable referencing the models and worlds, I will have both repositories models and worlds on the same GZ_SIM_RESOURCE_PATH variable? That is my only question right now

**Comment by srmainwaring** [comment]
> So at the end, on my environment variable referencing the models and worlds, I will have both repositories models and worlds on the same GZ_SIM_RESOURCE_PATH variable? That is my only question right now

Yes, that's right. `GZ_SIM_RESOURCE_PATH` should be a colon delimited list of resource paths that includes all the model and world directories you want Gazebo to search for resources.

**Comment by srmainwaring** [comment]
Closing as issue resolved.
