### ISSUE TITLE
Error Code 14: Msg: Parser configurations requested resolved uris, but uri [file://media/materials/scripts/gazebo.material] could not be resolved.

### ISSUE THREAD

**Issue by LaneaLucy** [ArduPilot/SITL_Models#135]
trying to do ```gz sim -v4 -r wildthumper_playpen.sdf```
getting the error ```Error Code 14: Msg: Parser configurations requested resolved uris, but uri [file://media/materials/scripts/gazebo.material] could not be resolved.```

found this, which might help:
https://community.gazebosim.org/t/migration-support-for-models-with-material-scripts/2471

**Comment by srmainwaring** [comment]
The `<script>` element needs to be removed. Previously the element was ignored, that may have changed in a recent Gazebo update.

A workaround is to comment / remove the `<script> ... </script> block here:

https://github.com/ArduPilot/SITL_Models/blob/f739c3f0e5e98b0cb0c2b5704e5737999a70c0a7/Gazebo/models/wildthumper/model.sdf#L34-L41

That's the only occurrence afaict.
